### PR TITLE
docs(readme): fix grammar

### PR DESCRIPTION
**Pull request by geenva**

### CODE REVIEW

**Comment by ammarsys** [comment]
Thank you for the PR! Could you also fix the following grammar errors,

- Line 46: Wording could be better, "... which is text to return as rainbow".
- Line 57, 58: Improperly spelled word "length".
- Line 60: Phrase "initial message" is missing an article.
- Line 58: "until" instead of "til" should be used here.
- Line 48: Improperly spelled word "parameters".
- Line 68: Noun "message" is missing an article, improperly spelled word "length".
- Line 69: Phrase "new message" is missing an article.
- Line 71: Improper article use, should be "a RGB" instead of "an RGB".
- Line 136: Improper article use, should be "an empty" instead of "a empty", "which enables" should be "that enables".
- Line 134: "includes" instead of "include".

Please follow up this PR with the changes listed above.

**Review by ammarsys — CHANGES_REQUESTED** [review]
Thank you for the PR! Could you also fix the following grammar errors,

- Line 46: Wording could be better, "... which is text to return as rainbow".
- Line 57, 58: Improperly spelled word "length".
- Line 60: Phrase "initial message" is missing an article.
- Line 58: "until" instead of "til" should be used here.
- Line 48: Improperly spelled word "parameters".
- Line 68: Noun "message" is missing an article, improperly spelled word "length".
- Line 69: Phrase "new message" is missing an article.
- Line 71: Improper article use, should be "a RGB" instead of "an RGB".
- Line 136: Improper article use, should be "an empty" instead of "a empty", "which enables" should be "that enables".
- Line 134: "includes" instead of "include".

Please follow up this PR with the changes listed above.

**Comment by geenva** [comment]
> Thank you for the PR! Could you also fix the following grammar errors,
> 
>     * Line 46: Wording could be better, "... which is text to return as rainbow".
> 
>     * Line 57, 58: Improperly spelled word "length".
> 
>     * Line 60: Phrase "initial message" is missing an article.
> 
>     * Line 58: "until" instead of "til" should be used here.
> 
>     * Line 48: Improperly spelled word "parameters".
> 
>     * Line 68: Noun "message" is missing an article, improperly spelled word "length".
> 
>     * Line 69: Phrase "new message" is missing an article.
> 
>     * Line 71: Improper article use, should be "a RGB" instead of "an RGB".
> 
>     * Line 136: Improper article use, should be "an empty" instead of "a empty", "which enables" should be "that enables".
> 
>     * Line 134: "includes" instead of "include".
> 
> 
> Please follow up this PR with the changes listed above.

Made changes according to your suggestions where I saw appropriate.

**Review by ammarsys — APPROVED** [review]

**Comment by ammarsys** [comment]
Thank you! Merged.

**Pull request merged**
